# Generated by Django 4.2.7 on 2024-07-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proggegruppe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='field_attributes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hidden_attributes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
